/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatComponent: typeof import('./src/components/ChatComponent.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    DoughnutChart: typeof import('./src/components/DoughnutChart.vue')['default']
    EntityList: typeof import('./src/components/EntityList.vue')['default']
    KpiCard: typeof import('./src/components/KpiCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OverviewGauge: typeof import('./src/components/OverviewGauge.vue')['default']
    ReadinessDashboard: typeof import('./src/components/ReadinessDashboard.vue')['default']
    ReadinessInput: typeof import('./src/components/ReadinessInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
  }
}
